version: '3'
services:
  redis-master:
    image: kilsoo75/redis-master
    deploy:
      restart_policy:
        condition: none
    networks:
      - webnet
  redis-slave:
    image: kilsoo75/redis-slave
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
    depends_on:
      - redis-master
    networks:
      - webnet
  redis-sentinel:
    image: kilsoo75/redis-sentinel
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
    depends_on:
      - redis-master
      - redis-slave
    networks:
      - webnet
  haproxy-redis:
    image: kilsoo75/haproxy-redis
    ports:
      - "7777:7777"
    depends_on:
      - redis-master
      - redis-slave
    networks:
      - webnet
  cloud-biz-frontend:
    image: kilsoo75/cloud-movie-frontend
    ports:
      - "8080:8080"
    depends_on:
      - redis-haproxy
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - redis-master
      - redis-slave
    networks:
      - webnet
networks:
  webnet:
