apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-movie-frontend-a
  namespace: redis-ha
spec:
  replicas: 5
  template:
    metadata:
      labels:
        svc: cloud-movie-frontend-a
    spec:
      containers:
      - name: cloud-movie-frontend
        image: kilsoo75/cloud-movie:1.1
        ports:
        - name: frontend-port
          containerPort: 8080
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-movie-frontend-b
  namespace: redis-ha
spec:
  replicas: 1
  template:
    metadata:
      labels:
        svc: cloud-movie-frontend-b
        stack: canary
    spec:
      containers:
      - name: cloud-movie-frontend
        image: kilsoo75/cloud-movie:1.2
        ports:
        - name: frontend-port
          containerPort: 8080
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-movie-frontend-a
  labels:
    name: cloud-movie-frontend-a
  namespace: redis-ha
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: "frontend-port"
    protocol: TCP
    name: http
  selector:
    svc: cloud-movie-frontend-a
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-movie-frontend-b
  labels:
    name: cloud-movie-frontend-b
  namespace: redis-ha
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: "frontend-port"
    protocol: TCP
    name: http
  selector:
    svc: cloud-movie-frontend-b
