apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    name: redis-master
  namespace: redis-ha
spec:
  ports:
  - port: 6379
    targetPort: "master-port"
  selector:
    backend: redis-master