apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-master
  namespace: redis-ha
spec:
  replicas: 1
  template:
    metadata:
      labels:
        backend: redis-master
    spec:
      containers:
      - name: redis-master
        image: kilsoo75/redis-master
        ports:
        - name: master-port
          containerPort: 6379
      restartPolicy: Always
      nodeSelector:
        beta.kubernetes.io/os: linux
        kubernetes.io/hostname: ip-172-31-9-170
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    name: redis-master
  namespace: redis-ha
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: "master-port"
    nodePort: 30022
  selector:
    backend: redis-master